# Stage 1: Build the React frontend
FROM node:20-alpine AS frontend-builder

WORKDIR /app

# Build args for environment variables (available during build)
ARG VITE_USE_MOCK=false
ARG VITE_DEFAULT_LAYOUT=single
ARG VITE_DEFAULT_INTERVAL_MS=5000
ARG VITE_DEFAULT_SHUFFLE=true
ARG VITE_DEFAULT_AUTOPLAY=true
ARG VITE_DEFAULT_OBJECT_FIT=cover
ARG VITE_DEFAULT_THEME=dark
ARG VITE_DEFAULT_SHOW_CLOCK=true
ARG VITE_DEFAULT_SHOW_WEATHER=false
ARG VITE_DEFAULT_SHOW_PROGRESS_BAR=true
ARG VITE_DEFAULT_SHOW_PHOTO_METADATA=true
ARG VITE_DEFAULT_FONT_SIZE=base
ARG VITE_DEFAULT_24_HOUR_FORMAT=false
ARG VITE_DEFAULT_WEATHER_LAT=51.5074
ARG VITE_DEFAULT_WEATHER_LNG=-0.1278
ARG VITE_DEFAULT_ALBUM_IDS=
ARG VITE_DEFAULT_PERSON_IDS=
ARG VITE_DEFAULT_LOCATION_COUNTRY=
ARG VITE_DEFAULT_LOCATION_STATE=
ARG VITE_DEFAULT_LOCATION_CITY=
ARG VITE_DEFAULT_TRANSITION_TYPE=fade
ARG VITE_DEFAULT_TRANSITION_DURATION=500

# Make them available as ENV for the build process
ENV VITE_USE_MOCK=$VITE_USE_MOCK
ENV VITE_DEFAULT_LAYOUT=$VITE_DEFAULT_LAYOUT
ENV VITE_DEFAULT_INTERVAL_MS=$VITE_DEFAULT_INTERVAL_MS
ENV VITE_DEFAULT_SHUFFLE=$VITE_DEFAULT_SHUFFLE
ENV VITE_DEFAULT_AUTOPLAY=$VITE_DEFAULT_AUTOPLAY
ENV VITE_DEFAULT_OBJECT_FIT=$VITE_DEFAULT_OBJECT_FIT
ENV VITE_DEFAULT_THEME=$VITE_DEFAULT_THEME
ENV VITE_DEFAULT_SHOW_CLOCK=$VITE_DEFAULT_SHOW_CLOCK
ENV VITE_DEFAULT_SHOW_WEATHER=$VITE_DEFAULT_SHOW_WEATHER
ENV VITE_DEFAULT_SHOW_PROGRESS_BAR=$VITE_DEFAULT_SHOW_PROGRESS_BAR
ENV VITE_DEFAULT_SHOW_PHOTO_METADATA=$VITE_DEFAULT_SHOW_PHOTO_METADATA
ENV VITE_DEFAULT_FONT_SIZE=$VITE_DEFAULT_FONT_SIZE
ENV VITE_DEFAULT_24_HOUR_FORMAT=$VITE_DEFAULT_24_HOUR_FORMAT
ENV VITE_DEFAULT_WEATHER_LAT=$VITE_DEFAULT_WEATHER_LAT
ENV VITE_DEFAULT_WEATHER_LNG=$VITE_DEFAULT_WEATHER_LNG
ENV VITE_DEFAULT_ALBUM_IDS=$VITE_DEFAULT_ALBUM_IDS
ENV VITE_DEFAULT_PERSON_IDS=$VITE_DEFAULT_PERSON_IDS
ENV VITE_DEFAULT_LOCATION_COUNTRY=$VITE_DEFAULT_LOCATION_COUNTRY
ENV VITE_DEFAULT_LOCATION_STATE=$VITE_DEFAULT_LOCATION_STATE
ENV VITE_DEFAULT_LOCATION_CITY=$VITE_DEFAULT_LOCATION_CITY
ENV VITE_DEFAULT_TRANSITION_TYPE=$VITE_DEFAULT_TRANSITION_TYPE
ENV VITE_DEFAULT_TRANSITION_DURATION=$VITE_DEFAULT_TRANSITION_DURATION

# Copy package files
COPY package*.json ./
COPY tsconfig*.json ./
COPY vite.config.ts ./
COPY eslint.config.js ./

# Install all dependencies (including devDependencies for build)
RUN npm ci

# Copy source code
COPY src/ ./src/
COPY public/ ./public/
COPY index.html ./

# Build the frontend (creates /app/dist)
RUN npm run build

# Stage 2: Prepare server dependencies
FROM node:20-alpine AS server-deps

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install only production dependencies
RUN npm ci --omit=dev

# Stage 3: Production runtime
FROM node:20-alpine AS production

WORKDIR /app

# Copy production dependencies
COPY --from=server-deps /app/node_modules ./node_modules

# Copy server source
COPY src/server ./src/server
COPY tsconfig.server.json ./

# Copy built frontend from builder stage
COPY --from=frontend-builder /app/dist ./dist

# Copy package.json for module resolution
COPY package.json ./

# Expose the port
EXPOSE 3000

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD node -e "require('http').get('http://localhost:3000', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"

# Run the server using tsx (TypeScript executor)
CMD ["npx", "tsx", "src/server/index.ts"]
